### ISSUE TITLE
number of epochs 

### ISSUE THREAD

**Issue by muhammedeltabakh** [mdalai/Deep-Learning-projects#1]
I think your neural network should iterate for a number of epochs. your current code is not making any use of number of epochs you can remove it and it will give the same result I guess

**Comment by mdalai** [comment]
hi thanks for the message. Which code,  please?

**Comment by muhammedeltabakh** [comment]
https://github.com/mdalai/Deep-Learning-projects/tree/master/wk5-speed-dating

**Comment by mdalai** [comment]
That is a good catch. Thanks a lot. I was wondered why it was doing not good. I will fix it. Thank again.

**Comment by mdalai** [comment]
Epochs and SGD are adopted. The NN prediction improve a lot. Thanks.
